before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp .sample.env .env
  - psql -c 'create database "rwc_test";' -U postgres
  - CODECLIMATE_REPO_TOKEN=d198b41bf631d7e64a50854b77f0b0680d5bc6c933e1c432ba6d7e10c6b5f090
  
branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  campfire:
    on_failure:
      - always
    on_success:
      - change
    template:
      - '(%{branch} - %{author}): %{message} - %{build_url}'
  email:
    - false
rvm:
  - 2.1.2
addons:
  postgresql: "9.3"

