development: &default
  adapter: postgresql
  database: rwc_development_prod_data
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

test:
  <<: *default
  database: rwc_test
